name: Build macOS DMG

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 PyInstaller Pillow
        
    - name: Create app icon
      run: |
        echo "Checking for simpleeditor.png:"
        ls -la simpleeditor.png || echo "simpleeditor.png not found"
        echo "Creating app icon..."
        python create_icon_optimized.py
        echo "Checking for created icon files:"
        ls -la *.icns *.png 2>/dev/null || echo "No icon files found"
        echo "Checking iconset directory:"
        ls -la "Simple Editor.iconset/" 2>/dev/null || echo "No iconset directory found"
        
    - name: Build macOS app
      run: |
        echo "Checking for icon before build:"
        ls -la icon.icns || echo "icon.icns not found before build"
        echo "Using the simple build script..."
        chmod +x build_simple_macos.sh
        ./build_simple_macos.sh
        
    - name: Rename DMG for release
      run: |
        # Rename DMG to include version
        if [ -f "Simple Editor-1.0.0.dmg" ]; then
          mv "Simple Editor-1.0.0.dmg" "Simple Editor-${{ github.ref_name }}.dmg"
        fi
        
    - name: Upload DMG artifact
      uses: actions/upload-artifact@v4
      with:
        name: Simple-Editor-macOS-${{ github.ref_name }}
        path: Simple Editor-*.dmg
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: Simple Editor-*.dmg
        name: Simple Editor ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: |
          ## Simple Editor ${{ github.ref_name }}
          
          A simple, fast text editor for macOS with a subtle animated rainbow border.
          
          ### Features
          - Fast and lightweight text editing
          - Plain text paste (strips all formatting)
          - Subtle animated rainbow border
          - Cross-platform compatibility
          - No external dependencies required
          
          ### Installation
          1. Download the DMG file
          2. Open the DMG
          3. Drag "Simple Editor" to your Applications folder
          4. Launch from Applications or Spotlight
          
          ### System Requirements
          - macOS 10.15 or later
          - No additional dependencies required
          
          ### Note
          If you see a security warning when first opening the app:
          1. Right-click on "Simple Editor" in Applications
          2. Select "Open"
          3. Click "Open" in the security dialog
          4. The app will then open normally
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
