name: Build macOS DMG

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 PyInstaller
        
    - name: Create app icon
      run: python create_icon.py
      
    - name: Build macOS app
      run: |
        # Use a simpler PyInstaller command that avoids Xcode issues
        pyinstaller --onefile --windowed --name "Simple Editor" \
          --icon=icon.icns \
          --add-data "icon.icns:." \
          --add-data "src:src" \
          --hidden-import PyQt6.QtCore \
          --hidden-import PyQt6.QtGui \
          --hidden-import PyQt6.QtWidgets \
          --hidden-import PyQt6.sip \
          --osx-bundle-identifier com.simpleeditor.app \
          simple_editor_enterprise.py
        
    - name: Create app bundle manually
      run: |
        # Create proper app bundle structure
        mkdir -p "Simple Editor.app/Contents/MacOS"
        mkdir -p "Simple Editor.app/Contents/Resources"
        
        # Move the executable
        mv "dist/Simple Editor" "Simple Editor.app/Contents/MacOS/"
        
        # Create Info.plist
        cat > "Simple Editor.app/Contents/Info.plist" << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>Simple Editor</string>
            <key>CFBundleIdentifier</key>
            <string>com.simpleeditor.app</string>
            <key>CFBundleName</key>
            <string>Simple Editor</string>
            <key>CFBundleVersion</key>
            <string>1.0.0</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0.0</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleSignature</key>
            <string>????</string>
            <key>LSMinimumSystemVersion</key>
            <string>10.15.0</string>
            <key>NSHighResolutionCapable</key>
            <true/>
            <key>NSRequiresAquaSystemAppearance</key>
            <false/>
            <key>CFBundleDocumentTypes</key>
            <array>
                <dict>
                    <key>CFBundleTypeName</key>
                    <string>Text Document</string>
                    <key>CFBundleTypeRole</key>
                    <string>Editor</string>
                    <key>LSItemContentTypes</key>
                    <array>
                        <string>public.text</string>
                        <string>public.plain-text</string>
                    </array>
                    <key>CFBundleTypeExtensions</key>
                    <array>
                        <string>txt</string>
                    </array>
                </dict>
            </array>
        </dict>
        </plist>
        EOF
        
        # Copy icon if it exists
        if [ -f "icon.icns" ]; then
            cp "icon.icns" "Simple Editor.app/Contents/Resources/"
        fi
        
    - name: Create DMG
      run: |
        # Create DMG directory structure
        DMG_DIR="Simple Editor DMG"
        mkdir -p "$DMG_DIR"
        
        # Copy app to DMG directory
        cp -R "Simple Editor.app" "$DMG_DIR/"
        
        # Create Applications symlink
        ln -s /Applications "$DMG_DIR/Applications"
        
        # Create DMG
        DMG_NAME="Simple Editor-${GITHUB_REF_NAME}.dmg"
        hdiutil create -volname "Simple Editor" -srcfolder "$DMG_DIR" -ov -format UDZO "$DMG_NAME"
        
        # Clean up
        rm -rf "$DMG_DIR"
        
    - name: Upload DMG artifact
      uses: actions/upload-artifact@v3
      with:
        name: Simple-Editor-macOS-${{ github.ref_name }}
        path: Simple Editor-*.dmg
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: Simple Editor-*.dmg
        name: Simple Editor ${{ github.ref_name }}
        body: |
          ## Simple Editor ${{ github.ref_name }}
          
          A simple, fast text editor for macOS with a subtle animated rainbow border.
          
          ### Features
          - Fast and lightweight text editing
          - Plain text paste (strips all formatting)
          - Subtle animated rainbow border
          - Cross-platform compatibility
          - No external dependencies required
          
          ### Installation
          1. Download the DMG file
          2. Open the DMG
          3. Drag "Simple Editor" to your Applications folder
          4. Launch from Applications or Spotlight
          
          ### System Requirements
          - macOS 10.15 or later
          - No additional dependencies required
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
