name: Build macOS DMG

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 PyInstaller Pillow
        
    - name: Build macOS app
      run: |
        # Use the simple build script
        chmod +x build_simple_macos.sh
        ./build_simple_macos.sh
        
    - name: Rename DMG for release
      run: |
        # Rename the DMG to include the version number
        if [ -f "Simple Editor-1.0.0.dmg" ]; then
          mv "Simple Editor-1.0.0.dmg" "Simple Editor-${GITHUB_REF_NAME}.dmg"
        fi
        
    - name: Upload DMG artifact
      uses: actions/upload-artifact@v4
      with:
        name: Simple-Editor-macOS-${{ github.ref_name }}
        path: Simple Editor-*.dmg
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: Simple Editor-*.dmg
        name: Simple Editor ${{ github.ref_name }}
        body: |
          ## Simple Editor ${{ github.ref_name }}
          
          A simple, fast text editor for macOS with a subtle animated rainbow border.
          
          ### Features
          - Fast and lightweight text editing
          - Plain text paste (strips all formatting)
          - Subtle animated rainbow border
          - Cross-platform compatibility
          - No external dependencies required
          
          ### Installation
          1. Download the DMG file
          2. Open the DMG
          3. Drag "Simple Editor" to your Applications folder
          4. Launch from Applications or Spotlight
          
          ### System Requirements
          - macOS 10.15 or later
          - No additional dependencies required
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
